### ISSUE TITLE
One Lock showing out of two

### ISSUE THREAD

**Issue by kapps7** [judge/homebridge-hikconnect#2] opened 2021-11-08 00:00 UTC
Hey I thought this is a better place to present the issue.

I have one lock of the two working but more showing from my gen 2 intercom as well as multiple other locks which seem to match the number of cameras I have in my nvr ie 9.

Wondering what I need to do to make the second lock work. Thanks
<img width="917" alt="Screen Shot 2021-11-08 at 10 59 37 am" src="https://user-images.githubusercontent.com/3489993/140666892-722af828-4224-4265-bcb2-77d8a429f8b4.png">
s

**Comment by judge** [comment] 2021-11-09 05:42
Hi,
That is strange, it seems these devices have lock somehow.
Can you help me debugging this?

- log in to Hik-Connect (https://www.hik-connect.com/) with your credentials
- open this url in a new tab: https://api.hik-connect.com/v3/userdevices/v1/devices/pagelist?groupId=-1&limit=100&offset=0&filter=TIME_PLAN,CONNECTION,SWITCH,STATUS,STATUS_EXT,WIFI,NODISTURB,P2P,KMS,HIDDN
- Send me the results via DM

**Comment by kapps7** [comment] 2021-11-09 06:13
Hey thanks for replying. I have the output you have asked form. Where is the dm option ;)

**Comment by judge** [comment] 2021-11-09 07:20
Thanks! It seems Github removed this feature a while ago. :( Anyway, I got the response, I'll have a look soon.

**Comment by judge** [comment] 2021-11-12 07:35
Hi!
I just published a new version which should solves your issue (at least I hope... sorry it took so long, I had to do some major refactor in the code to support multiple locks in the same lock channel (and also there is no documentation for this API))
Could you please check it?
Also it's a good idea to clear your devices caches first from the UI: Homebridge Settings / Remove Single Cached Accessory / search for your lock(s)

**Comment by kapps7** [comment] 2021-11-13 02:42
I cleared the cached accessories and now I only see two. I am just waiting for my client to return so I can test it properly. Thank you very much for putting in the work, this will be very useful to Hik owners. I have a suggestion: Most intercom owners who are using both the lock relays are most likely using one of them for a garage or gate. It would be useful as a setting to show one of the locks as a garage. 

As you know the garage accessory is treated differently in Homekit. I can use a dummy garage switch but it would be a cool feature.

I will get back to you soon after testing. Thanks Judge!

**Comment by judge** [comment] 2021-11-14 16:59
Actually I don't know what is the difference (in Homekit point of view) between garage and locks. Do you think these would be better as garage doors?
The way how it works now is kind of hacky as well because (at least in my case) the "lock" works as a latch. So whenever I unlock the door it will be unlocked for a certain amount of time (5-10 seconds) and then it automatically locks itself, so I had to manually set the status of the lock to locked after few seconds.

**Comment by kapps7** [comment] 2021-11-18 23:19
Hey mate, the early signs are good. Both locks are working. I am testing the auto lock 'hack' you are referring to see how ours performs. Ivms allows you to set that in the app so I guess thats an option for you down the track to add a setting to the plugin to allow uses to define the period for lock status.

Garage and locks are both secure accessories so they abide homekit rules for this category which include things like the owners device needs to be on the network and for an approval request via the phone if enabled. Garage however also has an obstruction sensor and has different features eg. via CarPlay. So if you are driving home with CarPlay and you have a garage accessory, it will automatically pop up when you approach home on your display to tap. This is not a user automation, just built into homekit

**Comment by judge** [comment] 2021-11-24 07:48
Thanks for the info!
Regarding the timeout, is it possible to set it by lock? So is it possible to set 5 seconds to one lock and 15 seconds to an another?
Choosing between Garage and Lock is a good idea but the problem is that Homebridge registers the devices dynamically and you have to decide what type of accessory you want to register in advance. I have no idea how can I make it configurable.

**Comment by judge** [comment] 2021-12-02 08:25
I'll close this for now, let me know if locks are still not working for you!

**Closed by judge** 2021-12-02 08:25 UTC
